# permissions for end users to view edgexes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgex-viewer-role
rules:
- apiGroups:
  - device.openyurt.io
  resources:
  - edgexes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - device.openyurt.io
  resources:
  - edgexes/status
  verbs:
  - get
