# permissions for end users to edit edgexes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgex-editor-role
rules:
- apiGroups:
  - device.openyurt.io
  resources:
  - edgexes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - device.openyurt.io
  resources:
  - edgexes/status
  verbs:
  - get
